spring:
  application:
    name: board

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        permittedNumberOfCallsInHalfOpenState: 5
#        registerHealthIndicator: true
